namespace SpriteKind {
    export const Gas = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(assets.image`galgaDart1`, mySprite, 0, -70)
    projectile.startEffect(effects.trail, 500)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    sprite.destroy(effects.bubbles, 10)
    otherSprite.destroy(effects.trail, 10)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Gas, function (sprite, otherSprite) {
    statusbar.value = 100
    otherSprite.destroy()
})
statusbars.onZero(StatusBarKind.Energy, function (status) {
    game.over(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    otherSprite.destroy(effects.spray, 500)
})
let myEnemy2: Sprite = null
let myEnemy: Sprite = null
let myFuel: Sprite = null
let projectile: Sprite = null
let statusbar: StatusBarSprite = null
let mySprite: Sprite = null
effects.starField.startScreenEffect()
mySprite = sprites.create(img`
    ...........8............
    ..........888...........
    .........88888..........
    .........88988..........
    .........88988..........
    .........88988..........
    .........88988..........
    .........88988..........
    .........88988..........
    .......888888888........
    .......999999999........
    ........5999995.........
    .........22222..........
    .........5.9.5..........
    ...........9............
    ...........9............
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
mySprite.setStayInScreen(true)
statusbar = statusbars.create(20, 4, StatusBarKind.Energy)
statusbar.attachToSprite(mySprite, -22, 0)
info.setScore(0)
info.setLife(4)
game.onUpdateInterval(5000, function () {
    myFuel = sprites.createProjectileFromSide(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 9 9 9 9 9 . . . . . . 
        . . . . 9 9 9 9 9 9 9 . . . . . 
        . . . 9 9 9 9 9 9 9 9 9 . . . . 
        . . 9 9 9 9 9 9 9 8 9 9 9 . . . 
        . . 9 9 9 9 9 9 9 9 7 9 9 . . . 
        . . 7 9 9 9 9 9 9 9 9 7 9 . . . 
        . . 7 9 9 9 9 9 9 9 9 7 9 . . . 
        . . 7 9 9 9 9 9 9 9 7 9 9 . . . 
        . . . 7 9 9 9 9 9 7 9 9 . . . . 
        . . . . 7 9 9 7 7 9 9 . . . . . 
        . . . . . 9 9 9 9 9 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, 0, 30)
    myFuel.x = randint(5, 155)
    myFuel.setKind(SpriteKind.Gas)
})
game.onUpdateInterval(1000, function () {
    myEnemy = sprites.createProjectileFromSide(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ..............eeee..............
        .......eeeeeeee55eee............
        ......ee55552222255eee..........
        ......ee5222455522255ee.........
        .....ee522454545542225e.........
        .....ee525455eee55452ee.........
        .....e55255e5455e5542ee.........
        .....e5545e54ee55e4525e.........
        .....e5555e5e55e555425e.........
        .....e5e45e4e45e5e5525e.........
        .....e5e24e54ee55e5225e.........
        .....e55445e5455e54255e.........
        .....ee55554eeee55525ee.........
        .....e55244555554422ee..........
        .....ee522224455522ee...........
        .....ee5555222222255e...........
        ......eeee555555555ee...........
        ........eeeeeeeeeeeee...........
        ............eeee................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, 0, 50)
    myEnemy.x = randint(5, 155)
    myEnemy.setKind(SpriteKind.Enemy)
    myEnemy2 = sprites.createProjectileFromSide(assets.image`UFO`, 0, 50)
    myEnemy2.x = randint(5, 155)
    myEnemy2.setKind(SpriteKind.Enemy)
})
game.onUpdateInterval(300, function () {
    statusbar.value += -1
})
